version: '3'
services:
  bot:
    build: . 
    container_name: 'transcripter_bot'
    depends_on:
      - mongo
    ports:
      - '3000:3000' 
    environment:
      - MONGO_URI=mongodb://mongo:27017/transcripter_bot
  mongo:
    image: 'mongo:4.4'
    container_name: 'mongo'
    ports:
      - '27100:27017'
    volumes:
      - ./data/dev/mongo:/data/db
